name: Resusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifacts-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying..."